language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "hIDkM2uwIFi+AqC32Zl3Vi7CdzpQlMFlv934pO1RdLFQqdElzqM4jCgtCnLJvzagnl3vfk8qcVCEPimjpMkT3dPyhDGi0M1fydQI04fg64rpF0xEbwirhNPaM3TnaQbLTtlinhRlBhJc5Qzlot96jvr/+YRdVz9UVcQX768W29pel36J5+QBCt/idF9Q1uVW9RFQeM5qKEQ99y4rdBnC+CyDHKU/UOvChX5XlciPxAxAqz+1qT20/nJXBOhqb3G4GBaO2LalXFzO9KD8hWQP86nOyJbr1yroFEUhLv7+Hu9b3V8BWWDdSSHQtD1bcj1wlb+q3jS0u1DmtoJEPTLODe3QHhSZNOLeNTQ4LbrbfgvtlbkWAL/lvYeywQ++Y2qwOhv0U7c2Yk9DP7xkDHE9oODd9sgy2pyys8i2vvp9IFHrD2091NMOU2UrO4oY6lzeDRyld4Iv9QULakPNozotdW5v+dPBAaItInATbzCWgeSMHsHUInTKT3KFhjZo2SL0f71bA0KDkgK2Vr2xe+D2s7VF27EsdA5TTKaNkix//Evo/vSSTOJqzok6YkrIfAa4KMBGsPrivGpHPEYqvozEL+hsIlsKXTMUwhOig3jbwOlAwmwhqWXwVlLnP3Jhvhnv+T2pB7t7zlbSNvdPjesxRNRVYt4D3gyQmucpHF9d854="
  api_key: # 83d0
    secure: "jSjzsplA2FL3zZeUXatP8RHDGCJYOt0gbRNlwHH10CTpsT5jY1cXuDePBZSs9ALyKsoNytjjclRvsTnu3Cew0hfhUB4bOr0r0i54Zu1UWX2FPUggfOmojBRuBjxCaAoXw6saaHBTBKyzO12YoR/vvu2CXC8CgSGOoONhBwWiGOug8Sao1erCli61MWCy2tG8T/6eHPwWtYsoJKGR0t0pDROzAEjTrNVum6+0F39tyi26SCy+wp3KVSilrFxQBrUOQrbA5W4WdNcgS4AfHMM3K3Zpo2tsVCjfstF1qzCLNGRB91RLuwKckGVkLSfB4HsTgQTbGULBuYJYiOIz3Kqw/WCdRrFSaWbd/pC+sjz3hpplvSKRRw7QJoMD0RgD9ucxWDWAnsDzReeNfFgwP8AcFETBbkwJD1IGgOchbRDPIyUwauEEuhnlPExqBALa608mDQd0/BuJItygg5uoTcc2MhPRHbWHvnaoTwRCxj0utUjhuNwuYJBcWY8U9ieFV0NGH6irvdH4OH89E/jt/Im0Keg/EjK8HBoNDQ/Q+MLbxaBLbbi7O3sqCk3+p9iEuzczDTluM3J6YY3WIJ9b+AHkTp8tnCAHrpo/aKl84YQrtDfz1kW/vz21cxUKnLxOO+N9ou44susxYdiU2WcVv9Bqk9KSdVrjpw0kbULBaAjapR8="
  on:
    tags: true
    node: lts/*
